from typing import Protocol

from mini_runbot.domain.models import Build


class BuildRepository(Protocol):
    def add(self, build: Build) -> None: ...

    def get(self, build_id: str) -> Build | None: ...

    def list(self) -> list[Build]: ...

    def update(self, build: Build) -> None: ...

    def delete(self, build_id: str) -> None: ...


class PortLeaseStore(Protocol):
    def try_acquire_port(self, build_id: str, port: int) -> bool: ...

    def release_port(self, build_id: str, port: int) -> None: ...

    def reconcile_port_leases(self) -> list[int]: ...
