from __future__ import annotations

from collections.abc import Callable
from copy import deepcopy
from importlib.resources import files
from pathlib import Path
from typing import Any

import typer
import yaml

from mini_runbot.domain.validation import SAFE_ALIAS, SAFE_REF

Prompt = Callable[..., Any]
Confirm = Callable[..., bool]


def load_example_config() -> dict[str, Any]:
    resource = files("mini_runbot").joinpath("resources/config.example.yaml")
    loaded = yaml.safe_load(resource.read_text(encoding="utf-8"))
    if not isinstance(loaded, dict):
        raise RuntimeError("Bundled example configuration is not a YAML mapping")
    return loaded


def collect_config(
    defaults: dict[str, Any],
    *,
    prompt: Prompt = typer.prompt,
    confirm: Confirm = typer.confirm,
) -> dict[str, Any]:
    config = deepcopy(defaults)
    config["database_url"] = prompt("SQLite database URL", default=config["database_url"])
    config["builds_root"] = prompt("Build workspace directory", default=config["builds_root"])
    config["odoo_image"] = prompt("Odoo image", default=config["odoo_image"])
    config["postgres_image"] = prompt("PostgreSQL image", default=config["postgres_image"])
    config["port_start"] = _prompt_int(
        "First preview port", int(config["port_start"]), 1024, 65535, prompt
    )
    config["port_end"] = _prompt_int(
        "Last preview port",
        int(config["port_end"]),
        int(config["port_start"]),
        65535,
        prompt,
    )
    config["command_timeout_seconds"] = _prompt_int(
        "Command timeout in seconds",
        int(config["command_timeout_seconds"]),
        1,
        None,
        prompt,
    )
    config["health_timeout_seconds"] = _prompt_int(
        "HTTP healthcheck timeout in seconds",
        int(config["health_timeout_seconds"]),
        1,
        None,
        prompt,
    )
    config["max_concurrent_builds"] = _prompt_int(
        "Maximum concurrent builds",
        int(config["max_concurrent_builds"]),
        1,
        None,
        prompt,
    )
    config["cleanup_interval_seconds"] = _prompt_int(
        "Cleanup interval in seconds (0 disables it)",
        int(config["cleanup_interval_seconds"]),
        0,
        None,
        prompt,
    )
    config["destroyed_retention_seconds"] = _prompt_int(
        "Destroyed-build retention in seconds (0 retains indefinitely)",
        int(config["destroyed_retention_seconds"]),
        0,
        None,
        prompt,
    )
    config["load_demo_data"] = confirm(
        "Load Odoo demo data", default=bool(config["load_demo_data"])
    )
    config["retain_failed_runtime"] = confirm(
        "Retain failed Docker runtimes", default=bool(config["retain_failed_runtime"])
    )
    config["repositories"] = _collect_repositories(
        defaults.get("repositories", {}), prompt=prompt, confirm=confirm
    )
    return config


def render_config(config: dict[str, Any]) -> str:
    header = (
        "# Generated by `mini-runbot init`. Keep this file outside version control.\n"
        "# Repository aliases are the only Git sources accepted from API or CLI requests.\n"
    )
    return header + yaml.safe_dump(config, sort_keys=False, allow_unicode=True)


def write_config_exclusive(output: Path, content: str) -> Path:
    destination = output.expanduser().resolve()
    if not destination.parent.is_dir():
        raise ValueError(f"Parent directory does not exist: {destination.parent}")
    try:
        with destination.open("x", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
    except FileExistsError as exc:
        raise FileExistsError(f"Configuration already exists: {destination}") from exc
    return destination


def _prompt_int(
    label: str,
    default: int,
    minimum: int,
    maximum: int | None,
    prompt: Prompt,
) -> int:
    while True:
        value = int(prompt(label, default=default, type=int))
        if value < minimum:
            typer.echo(f"Value must be at least {minimum}.", err=True)
            continue
        if maximum is not None and value > maximum:
            typer.echo(f"Value must be at most {maximum}.", err=True)
            continue
        return value


def _prompt_validated(
    label: str,
    default: str | None,
    validator: Callable[[str], bool],
    error: str,
    prompt: Prompt,
) -> str:
    while True:
        kwargs = {"default": default} if default is not None else {}
        value = str(prompt(label, **kwargs)).strip()
        if validator(value):
            return value
        typer.echo(error, err=True)


def _collect_repositories(
    example_repositories: object,
    *,
    prompt: Prompt,
    confirm: Confirm,
) -> dict[str, dict[str, Any]]:
    examples = example_repositories if isinstance(example_repositories, dict) else {}
    example_alias, example = next(iter(examples.items()), ("custom", {}))
    if not isinstance(example, dict):
        example = {}
    repositories: dict[str, dict[str, Any]] = {}
    if not confirm("Configure an allowed Git repository", default=True):
        return repositories

    first = True
    while len(repositories) < 10:
        alias_default = str(example_alias) if first else f"custom{len(repositories) + 1}"
        alias = _prompt_validated(
            "Repository alias",
            alias_default,
            lambda value: bool(SAFE_ALIAS.fullmatch(value)) and value not in repositories,
            "Use a unique safe alias: lowercase letters, digits, '_' or '-'.",
            prompt,
        )
        url_default = str(example.get("url", "")) if first else None
        source = _prompt_validated(
            "Git HTTPS/SSH URL or configured local path",
            url_default,
            bool,
            "Repository source cannot be empty.",
            prompt,
        )
        ref = _prompt_validated(
            "Default Git ref",
            str(example.get("default_ref", "16.0")),
            lambda value: bool(SAFE_REF.fullmatch(value)),
            "Git ref contains unsafe or unsupported characters.",
            prompt,
        )
        target = _prompt_validated(
            "Checkout target",
            str(example.get("target", alias)) if first else alias,
            lambda value: bool(SAFE_ALIAS.fullmatch(value))
            and all(item["target"] != value for item in repositories.values()),
            "Use a unique safe checkout target.",
            prompt,
        )
        addons_subpath = _prompt_validated(
            "Addons subdirectory",
            str(example.get("addons_subpath", ".")),
            _safe_relative_path,
            "Addons subdirectory must be relative and cannot contain '..'.",
            prompt,
        )
        allow_request_ref = confirm(
            "Allow callers to request other refs",
            default=bool(example.get("allow_request_ref", True)),
        )
        priority = _prompt_int(
            "Addons priority",
            int(example.get("addons_priority", 100)),
            0,
            None,
            prompt,
        )
        repositories[alias] = {
            "url": source,
            "default_ref": ref,
            "target": target,
            "addons_subpath": addons_subpath,
            "allow_request_ref": allow_request_ref,
            "addons_priority": priority,
        }
        first = False
        if len(repositories) == 10 or not confirm("Add another repository", default=False):
            break
    return repositories


def _safe_relative_path(value: str) -> bool:
    path = Path(value)
    return bool(value) and not path.is_absolute() and ".." not in path.parts
